on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
permissions:
 contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         repository: ${{ github.repository }}
         ref: 6.x
         token: ${{ github.token }}
         fetch-depth: 0
